### ISSUE TITLE
I used openjdk 10 to run it.

### ISSUE THREAD

**Issue by NGLSL** [java8/Java8InAction#23]
I used openjdk 10 to run it. Openjdk 8 can't compile and run

**Comment by nbu** [comment]
Same here. Project supposed to be for Java 8 In Action book and built on Java 8. But pom.xml forcibly requires 1.9 as source and target in maven-compiler-plugin configuration.

**Comment by vbhosle** [comment]
switch to previous commit to get first edition code.

`git reset --hard ae8122f433f90a8bfed7244cdf6f99271f1d1125`

**Comment by stvstvstv** [comment]
Title of book " Java 8 in Action" 
doesn't compile under java 8 
:-1:
