### ISSUE TITLE
有些方法找不到 Some method is undefined 

### ISSUE THREAD

**Issue by KitGavinx** [java8/Java8InAction#34]
class: lambdasinaction.chap10.OperationsWithOptional 
line 15  and  line 18
The method or(() -> {}) is undefined for the type Optional<Integer>

-- ----------
class: lambdasinaction.chap10.OptionalMain
line 21
The method flatMap(Function<? super Optional<String>,? extends Stream<? extends R>>) in the type Stream<Optional<String>> is not applicable for the arguments (Optional::stream)

--------
class: lambdasinaction.chap6.Grouping
line 36
The method flatMapping((<no type> dish) -> {}, toSet()) is undefined for the type Grouping

line 41
The method filtering((<no type> dish) -> {}, toList()) is undefined for the type Grouping
--- --------------
class: lambdasinaction.chap6.PartitionPrimeNumbers
line 36
The method takeWhile((<no type> i) -> {}) is undefined for the type Stream<Integer>

**Comment by manaatmoon** [comment]
I meet the same problems. The readme.md said this project should be based on JAVA 1.8, but actually the takeWhile is a new function for JAVA 1.9, and also source and target in the pom.xml are also 1.9, so i'm a little confused which java version should i use to run this project?

**Comment by xerZV** [comment]
@manaatmoon I've used Java 11.

**Comment by MABIY** [comment]
pom.xml compile plugin  source and target all 1.9 , but the project of java8.

**Comment by NiceSeason** [comment]
I meet the same problems ,too

**Comment by DeepaAC** [comment]
any solution i am also facing same problem when giving 1.8

**Comment by warriorSL2016** [comment]
java11 is ok
